feat: Add exit mechanism if linglong package installation fails

diff --git a/debian/deepin-desktop-environment-ll.postinst b/debian/deepin-desktop-environment-ll.postinst
--- a/debian/deepin-desktop-environment-ll.postinst
+++ b/debian/deepin-desktop-environment-ll.postinst
@@ -13,6 +13,10 @@ install_pkg(){
     for pkg in `cat $1 | grep -v "^#"`
     do
         ll-cli --no-dbus install ${pkg}
+		if [ $? -ne 0 ]; then
+			echo "Command failed. Exiting."
+			exit 1
+		fi
     done
 }
 
